In [5]:
import numpy as np
import pandas as pd
import os
import sys

## Question 1

https://github.com/giasmith/lab2

## Question 2

In [23]:
df = pd.read_csv('data/data_clean.csv')
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [32]:
df = pd.read_csv('data/data1.csv', skiprows=2)
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [38]:
df = pd.read_csv('data/data5.csv', skipfooter=2, engine='python')
df.tail(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

In [45]:
df = pd.read_csv('data/data2.txt',skiprows=[0,1,3])
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [55]:
df = pd.read_csv('data/data3.txt',skiprows=[0,1], sep="	")
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [60]:
rowname = 
colname = ['Country', 'Happiness score', 'Whisker-high', 
           'Whisker-low', 'Dystopia (1.92) + residual', 'Explained by: Social support',
           'Explained by: Health life expectancy', 
           'Explained by: Freedom to make life choices', 
           'Explained by: Generosity', 'Explained by: Perceptions of corruption']
df = pd.read_csv('data/data4.txt',sep="$", names = colname)
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: Social support,Explained by: Health life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [62]:
df = pd.read_csv('data/data6.dat')
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,999.000,999.000,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,999.000,...,1.582,999.000,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,999.000,0.683,0.284,0.408
3,Iceland,7.495,7.593,999.000,2.426,...,1.644,0.914,0.677,0.353,999.000
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [13]:
df = pd.read_excel('data/data7.xlsx')
df

  Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)
0          URL: http://worldhappiness.report/ed/2018

In [17]:
df = pd.read_stata('data/data8.dta')
df.head(5)

,country,happinessscore,whiskerhigh,whiskerlow,dystopia192residual,explainedbygdppercapita,explainedbysocialsupport,explainedbyhealthylifeexpectancy,explainedbyfreedomtomakelifechoi,explainedbygenerosity,explainedbyperceptionsofcorrupti
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [26]:
df = pd.read_spss('data/data9.sav')
df.head(5)

,country,happiness,whiskerhigh,whiskerlow,dystopia,gdpPC,socsupport,lifeexp,lifechoice,generous,corrupt
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [33]:
df = pd.read_sas('data/data10.xpt')
df.head(5)

,COUNTRY,HAPPINES,WHISKERH,WHISKERL,DYSTOPIA,EXPLAINE,EXPLAIN2,EXPLAIN3,EXPLAIN4,EXPLAIN5,EXPLAIN6
0,b'Finland',7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,b'Norway',7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,b'Denmark',7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,b'Iceland',7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,b'Switzerland',7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

## Question 3

In [38]:
import numpy as np
import requests
import json
import os

In [39]:
api_key = os.environ['nasa_key']
api_key

KeyError: 'nasa_key'

In [40]:
useragent_url = 'https://httpbin.org/user-agent'
r = requests.get(useragent_url)
useragent = json.loads(r.text)['user-agent']

In [ ]:
headers = {'X-API-Key': api_key,
          'User-agent': useragent,
          'From': 'nqj5zk@virginia.edu'} # Contact me

In [41]:
root = 'https://api.nasa.gov/neo/rest/v1/feed?'
start_date = '2022-10-01'
end_date = '2022-10-08'

endpoint = 'start_date={START_DATE}&end_date={END_DATE}&api_key={API_KEY}'

r = requests.get(root + endpoint,
                headers = headers)