In [349]:
import numpy as np
import pandas as pd
import os
import re
import sys
import time
from bs4 import BeautifulSoup
import collections
collections.Callable = collections.abc.Callable

## Question 1

https://github.com/giasmith/lab2

## Question 2

In [23]:
df = pd.read_csv('data/data_clean.csv')
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [32]:
df = pd.read_csv('data/data1.csv', skiprows=2)
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [45]:
df = pd.read_csv('data/data2.txt',skiprows=[0,1,3])
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [55]:
df = pd.read_csv('data/data3.txt',skiprows=[0,1], sep="	")
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,...,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,...,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [60]:
rowname = 
colname = ['Country', 'Happiness score', 'Whisker-high', 
           'Whisker-low', 'Dystopia (1.92) + residual', 'Explained by: Social support',
           'Explained by: Health life expectancy', 
           'Explained by: Freedom to make life choices', 
           'Explained by: Generosity', 'Explained by: Perceptions of corruption']
df = pd.read_csv('data/data4.txt',sep="$", names = colname)
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: Social support,Explained by: Health life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [38]:
df = pd.read_csv('data/data5.csv', skipfooter=2, engine='python')
df.tail(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
151,Yemen,3.355,3.448,3.262,1.106,...,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,...,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,...,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,...,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,...,0.627,0.145,0.065,0.149,0.076

In [62]:
df = pd.read_csv('data/data6.dat')
df.head(5)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,...,999.000,999.000,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,999.000,...,1.582,999.000,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,...,1.590,999.000,0.683,0.284,0.408
3,Iceland,7.495,7.593,999.000,2.426,...,1.644,0.914,0.677,0.353,999.000
4,Switzerland,7.487,7.570,7.405,2.320,...,1.549,0.927,0.660,0.256,0.357

In [13]:
df = pd.read_excel('data/data7.xlsx')
df

  Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)
0          URL: http://worldhappiness.report/ed/2018

In [17]:
df = pd.read_stata('data/data8.dta')
df.head(5)

,country,happinessscore,whiskerhigh,whiskerlow,dystopia192residual,explainedbygdppercapita,explainedbysocialsupport,explainedbyhealthylifeexpectancy,explainedbyfreedomtomakelifechoi,explainedbygenerosity,explainedbyperceptionsofcorrupti
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [26]:
df = pd.read_spss('data/data9.sav')
df.head(5)

,country,happiness,whiskerhigh,whiskerlow,dystopia,gdpPC,socsupport,lifeexp,lifechoice,generous,corrupt
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [33]:
df = pd.read_sas('data/data10.xpt')
df.head(5)

,COUNTRY,HAPPINES,WHISKERH,WHISKERL,DYSTOPIA,EXPLAINE,EXPLAIN2,EXPLAIN3,EXPLAIN4,EXPLAIN5,EXPLAIN6
0,b'Finland',7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,b'Norway',7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,b'Denmark',7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,b'Iceland',7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,b'Switzerland',7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

## Question 3

In [144]:
api_key = os.environ['nasa_key']
api_key

'B65e3MH2UfYLLe0rkQTUHspwRDfdyXUfGrzBTWkO'

In [145]:
useragent_url = 'https://httpbin.org/user-agent'
r = requests.get(useragent_url)
useragent = json.loads(r.text)['user-agent']

In [146]:
headers = {'X-API-Key': api_key,
          'User-agent': useragent,
          'From': 'nqj5zk@virginia.edu'} # Contact me

In [147]:
root = 'https://api.nasa.gov/neo/rest/v1/feed?'
start_date = '2022-10-01'
end_date = '2022-10-08'

endpoint = 'start_date={start_date}&end_date={end_date}.json'.format(start_date=start_date, 
                                                                     end_date = end_date)

r = requests.get(root + endpoint,
                headers = headers)
r

In [149]:
myjson = json.loads(r.text)
objects = pd.json_normalize(myjson)
objects

,element_count,links.next,links.previous,links.self,near_earth_objects.2022-10-03,near_earth_objects.2022-10-04,near_earth_objects.2022-10-01,near_earth_objects.2022-10-02,near_earth_objects.2022-10-07,near_earth_objects.2022-10-08,near_earth_objects.2022-10-05,near_earth_objects.2022-10-06
0,94,http://api.nasa.gov/neo/rest/v1/feed?start_dat...,http://api.nasa.gov/neo/rest/v1/feed?start_dat...,http://api.nasa.gov/neo/rest/v1/feed?start_dat...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...,[{'links': {'self': 'http://api.nasa.gov/neo/r...

## Question 4

### a. Pulling the current listed prices for houses for sale in Charlottesville from zillow.com

User-agent: *
Disallow: /post-real-estate-listings?zpid=
Disallow: /post-real-estate-listings/?zpid=
Disallow: /post-rental-listings?zpid=
Disallow: /postings/
Disallow: /postings/PostForSale.htm?

### b. Scraping current stock prices off of google.com/finance

### c. Copying the list of twitter accounts that each NBA player follows

In [ ]:
User-agent: *
Disallow: /search/realtime
Disallow: /search/users

### d. The lyrics to Lizzo's Good as Hell from https://genius.com/Lizzo-good-as-hell-lyrics

## Question 5

In [110]:
urltoscrape = 'https://genius.com/Lizzo-good-as-hell-lyrics'

###  a. Use requests and BeautifulSoup to scrape the lyrics to Good As Hell

In [165]:
r = requests.get(urltoscrape, 
                 headers= {'User-Agent': useragent,
                           'From': 'nqj5zk@virginia.edu'})
lizzohtml=BeautifulSoup(r.text, 'html.parser')

In [212]:
p1 = lizzohtml.find_all('div', id = 'lyrics-root-pin-spacer')[0].text
p1

"Good as Hell Lyrics[Chorus]I do my hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)[Verse 1]Woo, child, tired of the bullshitGo on, dust your shoulders off, keep it movingYes, Lord, tryna get some new shitIn there, swimwear, going-to-the-pool shitCome now, come dry your eyesYou know you a star, you can touch the skyI know that it's hard, but you have to tryIf you need advice, let me simplify[Pre-Chorus]If he don't love you anymoreJust walk your fine ass out the door[Chorus]I do my hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)(Feeling good as hell)Baby, how you feelin'? (Feelin' good as hell)See Lizzo LiveGet tickets as low as $44You might also like[Verse 2]Woo, girl, need to kick off your shoesGotta take a deep breath, time to focus on youAll the big fights, long nights that you been throughI got a bottle of tequila I been saving for youBoss up and change your lifeYou can have it all, no sacrificeI know he did you wrong, we can make it rightSo go and let it all hang out tonight[Pre-Chorus]'Cause he don't love you anymoreSo walk your fine ass out the door[Chorus]And do your hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell) (Show it off tonight)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell) (And we gon' be alright)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)[Pre-Chorus]Mmm, yeah, alrightListen, if he don't love you anymoreThen walk your fine ass out the door[Chorus]And do your hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell) (Woo-hoo)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell) (Show it off tonight)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell) (And we gon' make it right)Hair toss, check my nailsBaby, how you feelin'? (Feelin' good as hell)(Feelin' good as hell)Baby, how you feelin'? (Feelin' good as hell)28Embed"

### b. Use requests and BeautifulSoup to save the list of song lyric URLs in a Python list.

In [ ]:
r = requests.get(urltoscrape, 
                 headers= {'User-Agent': useragent,
                           'From': 'nqj5zk@virginia.edu'})
lizzohtml=BeautifulSoup(r.text, 'html.parser')

In [342]:
song_urls = []
p2 = lizzohtml.find_all('ol')[0]

for link in p2.find_all('a', attrs={'href': re.compile("https://")}):
    song_urls.append(link.get('href'))
    
song_urls

['https://genius.com/Lizzo-cuz-i-love-you-lyrics',
 'https://genius.com/Lizzo-like-a-girl-lyrics',
 'https://genius.com/Lizzo-juice-lyrics',
 'https://genius.com/Lizzo-soulmate-lyrics',
 'https://genius.com/Lizzo-jerome-lyrics',
 'https://genius.com/Lizzo-cry-baby-lyrics',
 'https://genius.com/Lizzo-tempo-lyrics',
 'https://genius.com/Lizzo-exactly-how-i-feel-lyrics',
 'https://genius.com/Lizzo-better-in-color-lyrics',
 'https://genius.com/Lizzo-heaven-help-me-lyrics',
 'https://genius.com/Lizzo-lingerie-lyrics',
 'https://genius.com/Lizzo-boys-lyrics',
 'https://genius.com/Lizzo-truth-hurts-lyrics',
 'https://genius.com/Lizzo-water-me-lyrics',
 'https://genius.com/Lizzo-good-as-hell-remix-lyrics']

### c. Build a spider

In [363]:
def time_2_scrape(song_urls):
    time.sleep(2.5)
    print("Scraping the queen's song:" + song_urls)
    r = requests.get(song_urls, headers= {'User-Agent': useragent,
                                            'From': 'nqj5zk@virginia.edu'})
    lizzohtml=BeautifulSoup(r.text, 'html.parser')
    lizzo_txt = lizzohtml.find_all('div', id = 'lyrics-root-pin-spacer')[0].text
    return lizzo_txt

In [364]:
songs = [time_2_scrape(u)for u in song_urls]

Scraping the queen's song:https://genius.com/Lizzo-cuz-i-love-you-lyrics
Scraping the queen's song:https://genius.com/Lizzo-like-a-girl-lyrics
Scraping the queen's song:https://genius.com/Lizzo-juice-lyrics
Scraping the queen's song:https://genius.com/Lizzo-soulmate-lyrics
Scraping the queen's song:https://genius.com/Lizzo-jerome-lyrics
Scraping the queen's song:https://genius.com/Lizzo-cry-baby-lyrics
Scraping the queen's song:https://genius.com/Lizzo-tempo-lyrics
Scraping the queen's song:https://genius.com/Lizzo-exactly-how-i-feel-lyrics
Scraping the queen's song:https://genius.com/Lizzo-better-in-color-lyrics
Scraping the queen's song:https://genius.com/Lizzo-heaven-help-me-lyrics
Scraping the queen's song:https://genius.com/Lizzo-lingerie-lyrics
Scraping the queen's song:https://genius.com/Lizzo-boys-lyrics
Scraping the queen's song:https://genius.com/Lizzo-truth-hurts-lyrics
Scraping the queen's song:https://genius.com/Lizzo-water-me-lyrics
Scraping the queen's song:https://genius.com/Lizzo-good-as-hell-remix-lyrics

In [370]:
songs[4]

"Jerome Lyrics[Intro]Woo, ohHere we go againUh-uh, hee-heeUh, look, listen, shut up[Chorus]Jerome, JeromeTake your ass homeAnd come back when you're grownJerome, JeromeGo on, take your ass homeWhere the peaches have thorns, ooh[Verse 1]Poor little babyWho told you that you stood a chance with this royalty?You're so sweet, bless your heartCan't let a pretty face distract me from businessAnd God as my witness, your ugly ass won't eitherI'm sorry, 2 AM photos with smileys and heartsAin't the way to my juicy partsBoy, thank me later, looks good on paperBut love isn't easy, so I'll do the hardest part[Chorus]Jerome, JeromeGo on, take your ass homeAnd come back when you're grownJerome, ooh, JeromeGo on, take your ass homeWhere the peaches have thorns[Verse 2]I never said I was perfectOr you don't deserve a good person to carry your baggageI know a few girls that can handle itI ain't that kind of chick, but I can call 'em for you if you wantI never said that you wasn't attractiveYour style and that beard, ooh, don't get me distractedI'm tryna be patient, and patience takes practiceThe fact is I'm leaving, so just let me have thisSee Lizzo LiveGet tickets as low as $44You might also like[Chorus]Jerome, JeromeTake your ass homeAnd come back when you're grown, ohJerome, ooh, JeromeGo on, take your ass homeWhere the peaches have thorns[Outro]Hee, hee, hee, hee, hee(Don't cry for me, baby)Hee, hee, hee, hee, heeHee, hee, hee, hee, hee(Oh, don't cry for me, baby)Hee, hee, hee, hee, hee, hee5Embed"

## Question 6

#### Step 1

#### Step 2

#### Step 3

#### Step 4

#### Step 5